### ISSUE TITLE
Set childApp name

### ISSUE THREAD

**Issue by JSteunou** [RoundingWellOS/marionette.toolkit#103]
A childApp might want to know under which name its parent application it is set :p

**Comment by paulfalgout** [comment]
So when a `childApp` is added to a parent perhaps a `_appName` is applied with some sort of `myApp.getAppName()` getter?

**Comment by JSteunou** [comment]
In my own old app I made an `appName` property without getter, but maybe it's not a good practice.

**Comment by paulfalgout** [comment]
I suppose I'm :+1: on it either way.

I think I'd like to see this in the 0.3.0 release  (which maybe should just be 1.0.0 at this point)
