### ISSUE TITLE
Forward start options

### ISSUE THREAD

**Issue by JSteunou** [RoundingWellOS/marionette.toolkit#106]
Playing with toolkit since couple days, I noticed that parent start options arent forward to childApp onStart or start event listeners.

I manage to get around that issue with this in a parent app

```
onStart: function(options) {
  this.getChildApp('foo').start(options);
}
```

even if `foo` has `startWithParent` set on `true`, as children are started after the parent own start event, it works. But I find this
1. useless boilerplate
2. dangerously linked to start event order

How do you guys manage it, is this an issue for you, what are your thoughts?

**Comment by JSteunou** [comment]
It's even worse than that :( `onStart` event does not get the options from `start()` call. I have to construct the parent with some options then call child start with `this.options`

**Comment by paulfalgout** [comment]
Hmm we rarely send the parent options to a child actually.   This is common pattern for you?

In most of our cases it's more like:
```js
onStart: function(options){
  options.region.show(this.layout);
  this.getChildApp('foo').start({
    region: this.layout.getRegion('fooRegion')
  });
}
```

**Comment by JSteunou** [comment]
Forget about my second comment, I did test too quickly, 1st comment and example was right.

**Comment by paulfalgout** [comment]
oh good.  I was worried for a second.. pretty sure options get passed :-)  

Check out this thread though for related option passing woes:

https://github.com/RoundingWellOS/marionette.toolkit/issues/99

**Comment by JSteunou** [comment]
it's not *that* common, but yeah sometimes I have weird flag I have to pass along descendants, but hey maybe it's just me having special case and using bad pattern.

**Comment by paulfalgout** [comment]
Sometime I think it is a totally reasonable pattern for some cases, but I think _most_ times its a bad pattern, so I'm a little weary of supporting it out of the box.  

Granted I think there are some bad or difficult situations, particularly around startWithParent where the childApp needs to be designed in such a way that it is aware of how it will be started (either with options in initialize for startWithParent, or options via onStart)  And I don't know that I have a great solution for it.  I want to make them more reusable. 

But for this issue I see it related to childViews on a collectionview.  In Marionette if you wanted the childviews to have the same options as the collection you would need to:
```js
var CollectionView = Marionette.CollectionView.extend({
  childView: ChildView,

  childViewOptions: function{
     return this.options;
  }
});
```

So maybe we should support a `childAppOptions`  Here though my concern is that with a `CollectionView` most times your `childViews` are all the same.. where with apps, they're likely all different.  So I very well may have a case where I want to pass the same options to _one_ of my children, but not all.

So it may be ideal to just require the configuration, even if it gets mildly boilerplatey.  

Thoughts?

**Comment by JSteunou** [comment]
I remember this issue on marionette https://github.com/marionettejs/backbone.marionette/issues/2026 where @cmaher goes quite far, with child global options that can be override per child. This could match your second though.

But I think that's not my use case. It's really passing along options from parent start to child start. On one hand I'm lazy and I like those being passing by automatically, on the other hand I dont like automagic, and I think you're right: it could be a bad pattern and pollute children options with useless data. Sometimes little boilerplate with explicit code is better.

**Comment by paulfalgout** [comment]
Ok with that note, I think I'll close this for now.  There is perhaps some interesting ideas around passing data between apps, but I want to be careful to not introduce feature complexity that could lead to poor practices.
