### ISSUE TITLE
improve github.io site

### ISSUE THREAD

**Issue by paulfalgout** [RoundingWellOS/marionette.toolkit#109]
We should have one

**Comment by paulfalgout** [comment]
auto'd it for a start: roundingwellos.github.io/marionette.toolkit

**Comment by JSteunou** [comment]
I am curious what did you use to generate this website?

**Comment by paulfalgout** [comment]
It was easier than I had expected.

When to here: https://pages.github.com/
Selected project site.

Then I loaded the readme into the markdown.

**Comment by JSteunou** [comment]
Hoo nice, I used github pages but did not the added auto generation from md. Very useful.

**Comment by TerrenceLJones** [comment]
Hey @paulfalgout , what improvement were you thinking on adding?

**Comment by TerrenceLJones** [comment]
@paulfalgout ☝️

**Comment by paulfalgout** [comment]
It'd be cool to have something that was styled specifically for this project and didn't look 100% like the github template

**Comment by paulfalgout** [comment]
meh the newer github one is fine
