### ISSUE TITLE
StateBehavior

### ISSUE THREAD

**Issue by paulfalgout** [RoundingWellOS/marionette.toolkit#117]
squareknot updated their state library to have a StateBehavior which essentially adds StateClass type functionality to a view via a marionette behavior.  https://github.com/Squareknot/marionette.state/blob/master/src/state.behavior.js

Simple enough idea, but I could certainly see it being useful in toolkit..  granted we keep our state mainly in our apps or utilize a component when those two things are combined.. but it might make sense to be able to add it to a view as well..  I do still find myself occasionally setting flags on a view that would be better if they triggered events. Thoughts @RoundingWellOS/roundingwell ?

**Comment by nerdpruitt** [comment]
:+1: I think there are some times that I have put logic in the app where really it could have gone in the view...I just do it because of the ease of the `StateModel` built into `StateClass`.

**Comment by paulfalgout** [comment]
This instead: https://github.com/RoundingWellOS/marionette.toolkit/issues/138
