### ISSUE TITLE
Automate npm package publishing

### ISSUE THREAD

**Issue by paulfalgout** [RoundingWellOS/marionette.toolkit#125]

**Comment by paulfalgout** [comment]
@TerrenceLJones any interest in figuring this out?  It'd be setting up a shell script like https://github.com/marionettejs/marionettejs.com/blob/master/ship.sh

And then it'd be nice to have a npm script alias like so: https://github.com/marionettejs/marionettejs.com/blob/master/package.json#L16

What would be particularly impressive is if it could run the publish command once in the main directory.. and then once in each directory of [/packages/](https://github.com/RoundingWellOS/marionette.toolkit/tree/master/packages) without having to hard code what those are... something like:  
`find . -type d -exec sh -c '(cd {} && COMMAND)' ';'`  Ref: http://stackoverflow.com/questions/7470165/how-to-go-to-each-directory-and-execute-a-command

But I expect that'll take some investigation to figure out if it works in this context.

You could test is using `ls` vs `npm publish` just to see that it is traversing the directories correctly.

**Comment by TerrenceLJones** [comment]
@paulfalgout Can you please review PR #126 that resolves this issue.
