### ISSUE TITLE
Very cool

### ISSUE THREAD

**Issue by ianmstew** [RoundingWellOS/marionette.toolkit#127]
@paulfalgout I happened to notice your `StateClass` just now.  It seems you and I have some similar ideas about state management :)  I would love to hear how you're using it in RoundingWell, because I'm always trying to improve my handling of state in the Squareknot app.

**Comment by paulfalgout** [comment]
Thanks.  Always up for chatting more about it.  Also we're hoping to release v1 with an intro blog post on how it is going in the coming week or so.  I really like what you had to say here: https://github.com/Squareknot/marionette.state/issues/5#issuecomment-111248107
Our goals I think were roughly to cover that list.

**Comment by ianmstew** [comment]
:+1: Looking forward to that blog post!
