### ISSUE TITLE
We need a resetState that doesn't cause change events

### ISSUE THREAD

**Issue by paulfalgout** [RoundingWellOS/marionette.toolkit#136]
We need to be able to give it a new state from a starting point.. for stopping and starting the app with a new state.. it doesn't mean the state _changed_ from what the app state was previously... it might just be a totally different app state.

**Comment by paulfalgout** [comment]
So I think possibly if we do https://github.com/RoundingWellOS/marionette.toolkit/issues/146 then we can just make this a `restart` that calls `stop` `initState` `start`

**Comment by TerrenceLJones** [comment]
This is dependent on #152.
