### ISSUE TITLE
Add ability to reset state without reinitializing

### ISSUE THREAD

**Issue by TerrenceLJones** [RoundingWellOS/marionette.toolkit#162]

**Comment by paulfalgout** [comment]
Note that this _should_ trigger change events and is essentially just an alias for

pseudo: `stateModel.set(stateModel.default)`

**Comment by TerrenceLJones** [comment]
Closing this issue as #163 has been merged into develop.

**Comment by TerrenceLJones** [comment]
Closing this issue as #163 has been merged into develop.
