### ISSUE TITLE
Component should extend Object

### ISSUE THREAD

**Issue by paulfalgout** [RoundingWellOS/marionette.toolkit#172]
But still support the `getRegion` API.  Mn v3's application is mainly about it's `start` which doesn't apply here, and it's `region` which in this case Application's `showView` would be pretty bad for a component.

**Comment by TerrenceLJones** [comment]
This seems wrong. You expressly said [here](https://github.com/RoundingWellOS/marionette.toolkit/commit/0fb2659b52b37b79bca58a0a633c00abce016741#commitcomment-17954615) that you wanted to use `this.showView`.

**Comment by TerrenceLJones** [comment]
Please also note: https://github.com/RoundingWellOS/marionette.toolkit/pull/166#issuecomment-227341795
