### ISSUE TITLE
We should throw the stop event after clearing running events

### ISSUE THREAD

**Issue by paulfalgout** [RoundingWellOS/marionette.toolkit#178]
Nothing should be listening once `stop` occurs.. if need be use `onBeforeStart`

https://github.com/RoundingWellOS/marionette.toolkit/blob/master/dist/marionette.toolkit.js#L822

**Comment by TerrenceLJones** [comment]
@paulfalgout Is this a breaking change? If not, why does is require a major release?

**Comment by paulfalgout** [comment]
It _is_ breaking, but perhaps unlikely to break anything.  I think you'd have to be triggering something in `onStop` possibly to cause an issue.  In some cases I think we were doing this.. like `this.getState().clear()` would have thrown events that would have been listened to.   In some ways perhaps this is better listed as a bug.. as that's really not what you would want to happen.. I doubt we depend on this functionality..  I could see an argument for calling this a `v2.0.1`?
