### ISSUE TITLE
AbstractApp/App Tests

### ISSUE THREAD

**Issue by paulfalgout** [RoundingWellOS/marionette.toolkit#18]
Tests should likely be broken up into:
- [x] app-lifecycle.spec.js
- [x] app-running-events.spec.js [currently](https://github.com/RoundingWellOS/marionette.toolkit/blob/d817b68cf2a3c1aa6593b13ae4b6bbf86b4862cd/test/unit/abstract-app.spec.js)
- [ ] app-child-manager.spec.js
- [ ] lifecycle-options (startWithParent, stopWithParent, startWhenInitialized, preventDestroy)

**Comment by TerrenceLJones** [comment]
Hey, I currently have PR #37 that fixes #35 and I'm going to start work on more tests for the App-Child-Manager.

**Comment by brentli1** [comment]
Let's call the test file app-child-manager.spec.js

**Comment by paulfalgout** [comment]
Just double check that #33 #36 and #32 are covered in these tests
