### ISSUE TITLE
Uncaught TypeError: Cannot read property 'apply' of undefined

### ISSUE THREAD

**Issue by nadvi** [RoundingWellOS/marionette.toolkit#191]
As-salamu-alikum

I am very new to marionette.Please pardon me if you get my issue stupid.
I have a module as follows

```
define(function (
					require
				){
						var tk=require("tk");
						var bb=require("bb");
						
						var ba = tk.App.extend({
							onStart: function(options){
								this.showView(options.view);
								bb.history.start();
								},
							onBeforeStart: function(options){
								this.model = this.options.data;
								},
							onBeforeStop: function(options){
									
								},
							onStop: function(options){
									
								}
						});
						
						return new ba(); 
				},
		function(
					err
				){
					//The errback, error callback
					//The error has a list of modules that failed
					var failedId = err.requireModules && err.requireModules[0];
					
					console.log("In err "+failedId);
						console.log(err);
				}
	);`  
```
the view is as follows

```
define(
	          function (
					require
				){

					var Mn = require('mt');
					var aview = Mn.View.extend({
						
					el:'.layout' ,
					template: false,
				
					return new aview();
				}
	);
```
I have got the following error 

Uncaught TypeError: Cannot read property 'apply' of undefined
    at child.showView (backbone.marionette.js:3309)
    at child.onStart (bap.js:9)
    at child.triggerMethod$1 [as triggerMethod] (backbone.marionette.js:159)
    at child.triggerStart (marionette.toolkit.js:865)
    at child.start (marionette.toolkit.js:810)
    at main.js:57
    at Object.execCb (require.js:1693)
    at Module.check (require.js:881)
    at Module.<anonymous> (require.js:1136)
    at require.js:134
Chrome point me at
```
  showView: function showView(view) {
    var region = this.getRegion();
    for (var _len = arguments.length, args = Array(_len > 1 ? _len - 1 : 0), _key = 1; _key < _len; _key++) {
      args[_key - 1] = arguments[_key];
    }
    return region.show.apply(region, [view].concat(args));
```
in backbone.marionette.js

Please help me to fix the problem.

Zazakallah khair for reading.

Allah-hafiz

Nadvi

**Comment by paulfalgout** [comment]
`showView` on a Toolkit.App is calling `showView` on `Marionette.Application`  That function needs a defined region on the App.
https://github.com/marionettejs/backbone.marionette/blob/master/docs/marionette.application.md#root-layout

So your code will need something like:
```js
var ba = tk.App.extend({
  region: '.container',
  onStart: function(options) {
    this.showView(options.view);
  }
```
which will put the view inside a `<div class="container"></div>`

However your view is setting the `el` to `.layout` which will attempt to attach the view to DOM that is already rendered on the page.
I assume that is still the case here in which case you may want to try:
```js
var ba = tk.App.extend({
  region: '.layout',
  onStart: function(options) {
    this.showView(options.view, { replaceElement: true });
  }
```
But.. if you can add a single wrapping `<div>` for a starting container in your HTML that is an easier setup than making your layout the top DOM element.

**Comment by nadvi** [comment]
Zazakallah khair for quick answer my issue.
But I get confused by this in another issue.Please pardon me .I have a code as follows
```
jQuery(function($) {
	var container = $('.layout');

	function layout() {
	       container.layout({
	                 resize: false,
		         type: 'border',
		          vgap: 1,
		          hgap: 1
		});
	};
       $(window).resize(layout);
});
```
i.e when the top window is resized the layout() will fire.My idea is to attach $(window) with the application and container with a view. Is it possible? Please give me a solution.

Zazakallah khair for reading.

Allah-hafiz

Nadvi
