### ISSUE TITLE
Attaching component with an application

### ISSUE THREAD

**Issue by nadvi** [RoundingWellOS/marionette.toolkit#193]
As-salamu-alikum

Zazakallah khair for sowing interest to my issue.

I am new to the marionette as well as marionette.toolkit so my issue may be very stupid. Please pardon me if my issue irritate you .

Marionette.toolkit component idea is excellent. Is it possible to attach a component to an application anyway instead of a  view directly which we do by calling showView()?

Zazakallah khair for reading with passion. 

Allah hafiz

Nadvi

**Comment by paulfalgout** [comment]
```js
var region = myApp.getRegion();
myComponent.showIn(region);
```

**Comment by nadvi** [comment]
Zazakallah khair for answering my issue.

Allah-hafiz

Nadvi
