### ISSUE TITLE
Sub Application

### ISSUE THREAD

**Issue by nadvi** [RoundingWellOS/marionette.toolkit#197]
As-salamu-alikum

Zazakallah khair for showing interest on my post.

I am very new to marionette as well as backbone.I am also very weak in programming as well as in English.

Would you like to explain the sub application concept in marionette in a single page blogging site prospective?I will  grateful to you.

Zazakallah khair again for reading my post by spending your valuable time with passion.

Allah hafiz

Nadvi.

**Comment by paulfalgout** [comment]
will handle this with https://github.com/RoundingWellOS/marionette.toolkit/issues/90 at some point
