### ISSUE TITLE
ToDo with marionette.toolkit and marionette.toolkit.routerapp

### ISSUE THREAD

**Issue by nadvi** [RoundingWellOS/marionette.toolkit#198]
As-salamu-alikum

Zazakallah khair for showing interest on my post.

I am very new to marionette as well as backbone.I would be grate for me and others like me if you re-right the ToDo app implemented with marionette in marionette.toolkit + marionette.toolkit.routerapp + requirejs.

Would you like to do it for us ?

Zazakallah khair again for reading my post.

Allah-hafiz

Nadvi

**Comment by paulfalgout** [comment]
I don't think the todo app will accept it actually because toolkit is a flavor of Mn, but I might do it on a fork
