### ISSUE TITLE
Component as controller

### ISSUE THREAD

**Issue by nadvi** [RoundingWellOS/marionette.toolkit#199]
As-salamu-alikum

Zazakallah khair for showing interest to post.

I am new to marionette development and studying its features for using it in a SPA blog.

My issue is is it possible to use marionette.toolkit component as a controller because I have got [here](https://github.com/RoundingWellOS/marionette.toolkit/blob/master/docs/component.md)

> The Component provides a consistent interface for which to package state-view-logic.

Though my knowledge is very poor in programming -nearly nothing I have also go through the marionette.toolkit dist code and found that component is directly extended from MarionetteObject and marionette doc most probably suggest to use marionette object instead of  controller.

Is it possible? please give me a example code of doing that.If your kind honor allow me it would be grate for me.

Zazakallah khair again for reading by spending your valuable time with passion.

Allah-hafiz

Nadvi

**Comment by paulfalgout** [comment]
Component should be used sparingly.  It is ideally a building block to create a reuseable widget such as a calendar, or tooltip, or something that is very encapsulated state/view logic such that it could likely be used in various different apps with no alterations.

I would use apps as controllers I suppose.  My main purpose for apps is to load data and create views.  The lifecycle of the app allows me to start up and clean up sets up apps that align with various view trees reducing worrying about memory leaks.

**Comment by nadvi** [comment]
As-salamu-alikum

Zazakallah khair for showing interest to post.

Would you like to give me a live example of registering an application as controller in a AppRouter.It would be very helpful for me,please.

Zazakallah khair again for responding my concern by spending your valuable time with passion.

Allah-hafiz

Nadvi
