### ISSUE TITLE
Consider a restartWithParent option

### ISSUE THREAD

**Issue by paulfalgout** [RoundingWellOS/marionette.toolkit#215]
when using `app.restart()` it can handle it's lifecycle to the parent differently.

I think we would want to default this value to `false`

**Comment by TerrenceLJones** [comment]
If a `parentApp` restarts, wouldn't that require a `childApp` to restart? Or can with this feature the former happen without the latter?

**Comment by paulfalgout** [comment]
Currently it would just stop the children, and the app would have to restart the children.  This would prevent that, so the parent would need to be responsible for not starting the child during a restart
