### ISSUE TITLE
Add toggleState

### ISSUE THREAD

**Issue by paulfalgout** [RoundingWellOS/marionette.toolkit#225]
#A pretty common pattern for state models since many data points are flags is
```js
this.setState('isFoo', !this.getState('isFoo'));
```
This certainly isn't a big deal, but is there any benefit to changing this to:
```js
this.toggleState('isFoo');
```
where like `toggleClass` you could alternately pass it a boolean in the 2nd arg like:
```js
this.toggleState('isFoo', this.ui.foo.is(':checked'));`
```
The difference between this last example and simply setting `isFoo` is that it will coerce the data to a boolean.  so think:
```js
modelEvents: {
  'change:phone'(model, phone) {
    this.toggleState('hasPhoneNumber', phone);
  }
}
```

@LisaManresa @wesmangum thoughts?

**Comment by wesmangum** [comment]
I think this is a great feature to add, especially the coercion.

**Comment by LisaManresa** [comment]
Agreed. This is a great convenience feature.

**Comment by wesmangum** [comment]
How should attributes that aren't on the state be handled? Example:
```
this.toggleState('nonexistentStateKey1');
this.toggleState('nonexistentStateKey2', this.ui.foo.is(':checked'));
```

**Comment by JSteunou** [comment]
That's funny because I had the case just yesterday!

@wesmangum 2 ways:

1. do nothing or even raise error
2. handle all falsy value like undefined then it would become `true` or *forced* value

**Comment by paulfalgout** [comment]
Perhaps follow the jquery toggleClass behavior

**Comment by LisaManresa** [comment]
How should we handle Number cases? There could be cases where we would want `0` to be considered truthy. We could add a third boolean argument that would consider any number a truthy value.

**Comment by paulfalgout** [comment]
I think jquery `toggleClass` is still probably the ideal example.  To me it looks like the behavior is the 2nd argument is either explicitly `false` or it toggles true

**Comment by paulfalgout** [comment]
I'm realizing now this would change my `modelEvents` example.  We'd need to add a `!!`, but I think that's a reasonable solution

**Comment by paulfalgout** [comment]
https://github.com/jquery/jquery/blob/f18ca7bfe0f5e3184bf1ed55daf1668702c5577a/src/attributes/classes.js#L101

Ah hmm so jQuery specifically handles only a boolean.. essentially if the 2nd arg is `true` or `false` it sets it.. otherwise it just flips the value. hmm..

**Comment by paulfalgout** [comment]
Ok sorry to think out loud on this issue... this is where I'm kind of landing.
```
this.toggleState('nonexistentStateKey1');
this.getState('nonexistentStateKey1'); // true
this.toggleState('nonexistentStateKey2', false);
this.getState('nonexistentStateKey2'); // false
this.toggleState('existingKey', 'hello');
this.getState('existingKey'); // true
this.toggleState('existingKey', 0);
this.getState('existingKey'); // false
this.toggleState('existingKey', undefined);
this.getState('existingKey'); // false
```
which would mean a check on `arguments.length` would need to be made prior to coercing the 2nd argument.
If there's only 1 argument then get the current value and `!` it and set the key to the flipped value.
If there are 2 arguments, coerce the 2nd argument with `!!` and set the key.

This would mean that for numbers you'd need to `!!` which I think might be easier to understand than adding a 3rd argument.  By default it's a loose check.. if you need it to be a strict check, coerce the values the way you need prior to passing them in.
