### ISSUE TITLE
event after children started

### ISSUE THREAD

**Issue by JSteunou** [RoundingWellOS/marionette.toolkit#228]
I'm in a case where `app#onStart` is too soon and would have a similar event but after all children are started.

I had to override `_startChildApps` which is considered private, to trigger an event after.

Is there a better way, or is this something that could be added into childApp mixin?

**Comment by paulfalgout** [comment]
hmm yeah I think that's reasonable.

FWIW `onStart` will be first, but `app.on('start'` should happen after the built in one that starts the children

**Comment by paulfalgout** [comment]
After some discussion I think we're 👎 on implementing this.  There are too many caveats for really understanding when all children are started.  yes there's a single function that _might_ start all of the children, it will introduce an event that can't really be trusted depending on various states of child apps.  So for now I think we'll document adding `this.on('start'` event handler inside `initialize` as opposed to `onStart` as a way to get an event handler after everything internally has been run.

**Comment by JSteunou** [comment]
That's a good compromise, thank you @paulfalgout ;)

**Comment by paulfalgout** [comment]
This'll actually be fixed in v5
